### ISSUE TITLE
[Enhancement] Automate Posting to Youtube

### ISSUE THREAD

**Issue by Ahsan221B** [karim0sec/Bulk-Tiktoks-Downloader#22]
Maybe consider adding automated posting to youtube to automate the entire fabrication process.

We don't necessarily have to use Youtube Data API to post on YT. We can also use Firefox with Selenium support to automatically upload videos to youtube as they are downloaded. I think it will be a worthy addition to the project.

I can do this in Python, but I am not sure how to do it in JavaScript, although I am sure it's easier with JS since there are plenty of resources available.

**Comment by karim0sec** [comment]
That's so cool i had something like that but YouTube data API had some restrictions now i should try version 5 of it, i will replace snaptik for TikTok real API first, my friend just made simple [Reddit2Discord](https://github.com/khaled-ashraf-dev/Reddit-Post-Notifier-For-Discord) i think you might like that

**Comment by karim0sec** [comment]
seem Tiktok api is blocked verify devices now yesterday i tested it in another repo and worked, i keep it loop on snaptik but clean that messy code

**Comment by karim0sec** [comment]
there is no point it require client id and stuff for each user , this [repo](https://github.com/nmaties/video-uploader-youtube) do same by a loop on the task

**Comment by Ahsan221B** [comment]
> 



> there is no point it require client id and stuff for each user , this [repo](https://github.com/nmaties/video-uploader-youtube) do same by a loop on the task

That's the beauty of Selenium. We don't have to use Youtube Data API at all. We can just write a script, open our browser, and the script will then post all the videos for us by using a headless browser taking the credentials from whatever Youtube channel is logged in our Selnium Firefox profile. I am currently doing this on Python and it's working flawlessly. Maybe I can write a crossfunctional script that can take the downloaded videos from the current project and then post them on youtube daily using the python script? What do you think?

**Comment by karim0sec** [comment]
puppeteer same as selenium google just have many restrictions against browsers bots, the good thing about it that you can open browser anytime to solve google captcha then continue automate uploading i made [this](https://github.com/karim0sec/SimpleYTUploader) check it out

**Comment by EdricSon** [comment]
Can you give more instructions on how to use it? I don't know how to use it, the instructions are very sketchy and incomplete  https://github.com/karim0sec/SimpleYTUploader
