### ISSUE TITLE
Please fix the code

### ISSUE THREAD

**Issue by daltonjames777** [karim0sec/Bulk-Tiktoks-Downloader#23]
YOU have made some changes to the code, with the latest changes and information on how to install the code, I got an error after downloading some videos 👇

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1535:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:949:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:730:12)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'CERT_HAS_EXPIRED'
}

I also tried the old installation method, which was this
+ npm i puppeteer
+ npm install puppeteer puppeteer-extra
+ npm install puppeteer-extra-plugin-stealth puppeteer-extra-plugin-adblocker),
 but even here I got a different error code than the one above, the error code 👇

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 139.177.240.194:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '139.177.240.194',
  port: 443
}

I have used your script for months without any problems, the last two weeks I have always encountered problems, these two days I have been unable to do so since the above errors appear, if it is possible to fix it again, I would be very grateful, thank you!

**Comment by karim0sec** [comment]
![image](https://user-images.githubusercontent.com/92269255/197236652-77512fa7-bb56-441c-a04a-b822a6fee149.png)
i think you should delete the project and try to reinstall it again
add blocker no longer used

install it like that
git clone https://github.com/karim0sec/Bulk-Tiktoks-Downloader/

if you don't have git then download zip file and extract it

in terminal project directory only use 

npm i

**Comment by daltonjames777** [comment]
it is possible to download 10-60 videos, then it stops, I've tried it several times, but it always stops downloading more videos. is there any technique to understand which videos have been downloaded and to resume the download from where it was left because it stops and starts again from the beginning? (I deleted the project and installed it again as you explained above) Thank you!
![Capture](https://user-images.githubusercontent.com/115239529/197353616-b2138f73-0853-4938-8261-b8239bdb7a2d.PNG)

**Comment by karim0sec** [comment]
well i updated code but haven't test it may you test it again after pull repo and using `npm i` in directory command line?

and before do that please run `npm install -g npm` to upgrade your npm version

**Comment by daltonjames777** [comment]
It worked perfectly for two days, but as I understand it, the error comes from the changes Snaptik has made on its website, if I am right and this is the reason, I would be very grateful if you could explain it to me or a ready video, which shows that how can I change the selection in the code, since I could make this change myself, without asking you, since I have become very annoying these days!
![Capture](https://user-images.githubusercontent.com/115239529/197550383-2e728f10-3846-4f68-97b1-5b825ff6e2b5.PNG)

**Comment by daltonjames777** [comment]
It worked perfectly for two days, but as I understand it, the error comes from the changes Snaptik has made on its website, if I am right and this is the reason, I would be very grateful if you could explain it to me or a ready video, which shows that how can I change the selection in the code, since I could make this change myself, without asking you, since I have become very annoying these days!
![Capture](https://user-images.githubusercontent.com/115239529/197551150-97431f35-47aa-4739-b0d1-c1b04bd9c4c1.PNG)

**Comment by karim0sec** [comment]
updated
