### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by daltonjames777** [karim0sec/Bulk-Tiktoks-Downloader#25]
Hello, I came across a website where I can download videos in HD (https://musicaldown.com/en), I tried for two days to change the selectors, but I can't, I would be very grateful if the selectors can be changed, ( if it took a while to change them), and be offered as a third method in the script, along with snaptik. I believe the time should be longer because the HD download took more time.

When you find the time and if it is easy to make this change, I would be grateful, respect for your work, I really appreciate it!
![Capture](https://user-images.githubusercontent.com/115239529/198312202-56e8444b-c013-4b83-8fda-a4776bc7fc40.PNG)

**Comment by karim0sec** [comment]
don't forget to change `headless: false` to `headless: true`
farther issues use puppeteer [documentation](https://pptr.dev/)

**Comment by daltonjames777** [comment]
Hello, you did a good job but unfortunately it doesn't work, I tried it with headless: true, and I got an error, I tried it with headless: false to see where the error was, everything seemed ok, until it found it successfully the video, but when it had to start downloading it gave an error, and I'm very angry that I don't have the right knowledge to correct it myself. If you could correct it that would be fantastic and a job well done!
![Capture](https://user-images.githubusercontent.com/115239529/198626942-1750f01b-0609-4745-beae-785f59b25a87.PNG)
