### ISSUE TITLE
Please fix the code

### ISSUE THREAD

**Issue by quang1321** [karim0sec/Bulk-Tiktoks-Downloader#27]
E:\Work\Video>node allvideosuser https://www.tiktok.com/@chongsalyy
now it downloading 1472 video
Descriptions Saved!
./@chongsalyy/7159484187030932762.mp4 Saved!
Done
./@chongsalyy/7159417688131980571.mp4 Saved!
Done
./@chongsalyy/7159132277648166171.mp4 Saved!
Done
./@chongsalyy/7159026856048479514.mp4 Saved!
Done
./@chongsalyy/7158765377076399386.mp4 Saved!
Done
./@chongsalyy/7158688804981820698.mp4 Saved!
Done
./@chongsalyy/7158450145946848539.mp4 Saved!
Done

E:\Work\Video\node_modules\node-fetch\lib\index.js:273
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://api2.musical.ly/aweme/v1/feed/?aweme_id=7158418146473364762&version_code=262&app_name=musical_ly&channel=App&device_id=null&os_version=14.4.2&device_platform=iphone&device_type=iPhone9 reason: Unexpected end of JSON input
    at E:\Work\Video\node_modules\node-fetch\lib\index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getvideourl (E:\Work\Video\allvideosuser.js:89:19)
    at async main (E:\Work\Video\allvideosuser.js:82:21) {
  type: 'invalid-json'

**Comment by karim0sec** [comment]
i update it but can't test my internet not stable can u try again?
