### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by daltonjames777** [karim0sec/Bulk-Tiktoks-Downloader#28]
![Capture1](https://user-images.githubusercontent.com/115239529/198731471-edafd988-9017-428a-96ae-c9d64205489c.PNG)

**Comment by daltonjames777** [comment]
I'm sorry for bothering you again my friend, I tried to modify it several times but it doesn't work, you changed node modules and always got an error, the script you gave me (https://pastebin.com/raw/emnA4viQ) doesn't seem to work compatible with node modules, can you zip the whole project together with suitable node modules for this script https://pastebin.com/raw/emnA4viQ

I have tried with some previous node modules that you have published, but I always get a different error!
Thank you for everything you have helped me!!!

**Comment by karim0sec** [comment]
if it breaks i don't open issue again here please it not related to my script now
heres the zip file after extract it in it's directory use npm i https://www.mediafire.com/file/9upikkzvlrjdaaf/final.zip/file
