### ISSUE TITLE
Update name folder and name video

### ISSUE THREAD

**Issue by bpham1912** [karim0sec/Bulk-Tiktoks-Downloader#29]
Hi, I'm from Vietnam.
I am very impressed with your project. I used it and changed some items to make it more convenient.
You can refer to it

Dear.

**I updated your lines 95 and 96 to after I found out you got an error while downloading the video i = 2**

![image](https://user-images.githubusercontent.com/46698873/198874012-317041ea-cf21-496b-a78b-53ff9df5e322.png)

**Next, I changed line 123. Video name updated as description of tiktok video**

![image](https://user-images.githubusercontent.com/46698873/198874026-1a55338b-a2d0-439d-8983-32456856725f.png)

**results after editing!**

![image](https://user-images.githubusercontent.com/46698873/198873922-a1126527-d417-4d2e-8647-fd8521159cd7.png)

**Comment by karim0sec** [comment]
i see but people want unique identifier also , i made that script for one simple task and merge it with my [SImpleYTUploader](https://github.com/karim0sec/SImpleYTUploader)  but seems youtube not care about hashtag shorts anymore they just pick less than or equal to 60 sec videos
