### ISSUE TITLE
I have this bug in the process of using it, how should I fix it?

### ISSUE THREAD

**Issue by goodbyebug** [karim0sec/Bulk-Tiktoks-Downloader#30]
Hi, what directory are the downloaded videos saved in? I have this bug in the process of using it, how should I fix it?
![L_3 4 JA{5CZRXTNV`I}5Y7](https://user-images.githubusercontent.com/65641677/198986858-519276f5-5e4d-4626-b278-d7b9a2ed2da6.png)

**Comment by quang1321** [comment]
me too

**Comment by quang1321** [comment]
![image](https://user-images.githubusercontent.com/37654689/199027248-06e3fb62-e536-4caa-bd7d-2ee441035648.png)

**Comment by karim0sec** [comment]
not sure it works fine with me seems your ip blocked by tiktok or something
![image](https://user-images.githubusercontent.com/92269255/199067350-a4ba4690-99bc-45b0-9ac6-a43b63e6f284.png)

remove node_modules download latest package-lock.json and bulktok.js

use npm i

to install all dependencies

if error didn't fix try my [another project ](https://github.com/karim0sec/tiktokdl) it way more faster

**Comment by Getruk** [comment]
Doesn't download more than 30 videos.

**Comment by karim0sec** [comment]
> Doesn't download more than 30 videos.

try [tiktokdl](https://github.com/karim0sec/tiktokdl)

**Comment by Getruk** [comment]
The other project is the same.
Finds only 30 videos.
